---
title: "Social Media and Teens"
author: "Caroline Alexander and Elizabeth Slade"
format: revealjs
editor_options: 
  chunk_output_type: console
---

```{r}
# include: FALSE

library(tidyverse)
YRBS <- read_csv( "yrbs.csv" )
```

## Introduction

- How often do teens use social media?
- How does social media affect teens? 
- 

## How often do you use social media?

```{r}
# make your bar chart here
social_media <- YRBS |>
  select( q80 ) |>
  drop_na( q80 ) |> 
  mutate( q80 = as.character(q80) ) |> 
  mutate( q80 = case_when( q80 == "1" ~ "I do not use social media",
                           q80 == "2" ~ "A few times a month", q80 == "3" ~ "About once a week", q80 == "4" ~ "A few times a week", q80 == "5" ~ "About once a day", q80 == "6" ~ "Several times a day", q80 == "7" ~ "About once an hour", q80 == "8" ~ "More than once an hour" )) |>
  mutate( q80 = factor( q80, 
                        levels = c( "I do not use social media", "A few times a month", "About once a week", "A few times a week", "About once a day", "Several times a day", "About once an hour", "More than once an hour")))

ggplot(social_media) +
  geom_bar(aes( q80 )) +
  coord_flip() +
  labs( x = " ", y = "Number of Responses")

```

## During the past 12 months, have you ever been electronically bullied? 

```{r}
# make your bar chart here 
ggplot(YRBS) +
  geom_bar(aes( q25 )) +
  coord_flip() +
  labs( x = "Yes                                                No", y = "Number of Responses")
```




